version: 2

sources:
  - name: hbi
    database: hbi_db
    schema: raw
    tables:
      - name: hr_raw
        columns:
          - name: employeeid
            tests:
              - not_null
              - unique

models:
  - name: stg_employees
    description: "Staging table for employee data"
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique

  - name: stg_work_profile
    description: "Staging table for work profile data"
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique

  - name: stg_sentiment
    description: "Staging table for sentiment data"
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique       