version: 2

sources:
  - name: hbi
    database: semantic_layer
    schema: raw_db
    tables:
      - name: hr_raw
        columns:
          - name: employeeid
            tests:
              - not_null
              - unique

  - name: transformed_hbi
    database: semantic_layer
    schema: raw_db
    tables:
        - name: transformed_hr_raw
          columns:
            - name: employeeid
              tests:
                - not_null

models:
  - name: dim_employees
    description: "Dimension table for employee data"

  - name: dim_job
    description: "Includes details about the position"

  - name: dim_performance
    description: "Staging table for sentiment data"

  - name: dim_salary
    description: "Includes all information related with employees salary"

  - name: fct_employees
    description: "Table including all data needed to evaluate the working profile of the employee."

  - name: mtr_employee
    description: "Model used to create semantic model for attrition metrics"

  - name: transformed_hr_raw
    description: "Model transformed using MinMax Scaler to be used in Machine Learning models." 

  - name: min_max_scaler
    description: "Model created to apply MinMax transformation within dbt."
    config:
      materialized: table
      tags: ['python']
      columns:
        - name: employee_id
          tests:
            - not_null
            
 