version: 2

sources:
  - name: hbi
    database: hbi_db
    schema: raw
    tables:
      - name: hr_raw
        columns:
          - name: employeeid
            tests:
              - not_null
              - unique

  - name: transformed_hbi
    database: hbi_db
    schema: dbt_abarrantes
    tables:
        - name: transformed_hr_raw
          columns:
            - name: employeeid
              tests:
                - not_null

models:
  - name: dim_employees
    description: "Dimension table for employee data"

  - name: dim_job
    description: "Includes details about the position"

  - name: dim_performance
    description: "Staging table for sentiment data"

  - name: dim_salary
    description: "Includes all information related with employees salary"

  - name: fct_employees
    description: "Table including all data needed to evaluate the working profile of the employee."

  - name: mtr_employee
    description: "Model used to create semantic model for attrition metrics"

  - name: transformed_hr_raw
    description: "Model transformed using MinMax Scaler to be used in Machine Learning models."
 